/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameTDR.java
 *
 * Created on 18/10/2010, 11:28:44 AM
 */

package formulario;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author PC10
 */
public class OrdenServicioDirlog extends javax.swing.JFrame {

    /** Creates new form JFrameTDR */
    public OrdenServicioDirlog() {
        initComponents();
        centrarFormulario();
        this.setDefaultCloseOperation(OrdenServicioDirlog.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        OrdenServicioDirlogPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnNuevaOrden = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnBuscarConsultor = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnNuevoConsultor = new javax.swing.JButton();
        btnBuscarOrden = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblImagenEscudo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Termino de Referencia");
        setName("jrTDR/LOG"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 468, -1, -1));

        OrdenServicioDirlogPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        OrdenServicioDirlogPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Documento de Conformidad a Logistica:");
        OrdenServicioDirlogPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Fecha:");
        OrdenServicioDirlogPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jTextField18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        OrdenServicioDirlogPanel.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 80, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Tipo Doc.:");
        OrdenServicioDirlogPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nº Doc.:");
        OrdenServicioDirlogPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Fecha:");
        OrdenServicioDirlogPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, -1, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        OrdenServicioDirlogPanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 90, 30));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar-icono-4961-16.png"))); // NOI18N
        btnEliminar.setText(" ELIMINAR ");
        OrdenServicioDirlogPanel.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 140, -1));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sincronizacion-actualiza-la-recarga-icono-4348-16.png"))); // NOI18N
        btnCancelar.setText(" CANCELAR ");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        OrdenServicioDirlogPanel.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 140, -1));

        btnGrabar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGrabar.setText("GRABAR ");
        OrdenServicioDirlogPanel.add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 120, -1));

        btnNuevaOrden.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevaOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir-vcard-icono-6408-16.png"))); // NOI18N
        btnNuevaOrden.setText("Nueva Orden");
        OrdenServicioDirlogPanel.add(btnNuevaOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 150, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Nombre del Proyecto :");
        OrdenServicioDirlogPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Nº Orden Servicio:");
        OrdenServicioDirlogPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("2º Entrega del proyecto");
        OrdenServicioDirlogPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        OrdenServicioDirlogPanel.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 90, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Fecha:");
        OrdenServicioDirlogPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("1º Entrega del plan de trabajo");
        OrdenServicioDirlogPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        OrdenServicioDirlogPanel.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 90, 30));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        OrdenServicioDirlogPanel.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 90, 30));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Fecha:");
        OrdenServicioDirlogPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Fecha:");
        OrdenServicioDirlogPanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("3º Evaluacion Previa");
        OrdenServicioDirlogPanel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Nombres:");
        OrdenServicioDirlogPanel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jTextField23.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });
        OrdenServicioDirlogPanel.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 220, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Apellidos:");
        OrdenServicioDirlogPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jTextField28.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });
        OrdenServicioDirlogPanel.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 380, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Telefono:");
        OrdenServicioDirlogPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        OrdenServicioDirlogPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 110, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Email:");
        OrdenServicioDirlogPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        OrdenServicioDirlogPanel.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 380, 30));

        jTextField29.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        OrdenServicioDirlogPanel.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 380, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Razon Social:");
        OrdenServicioDirlogPanel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("Cronograma de Entrega del Proyecto:");
        OrdenServicioDirlogPanel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        jTextField20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        OrdenServicioDirlogPanel.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, 80, 30));

        jTextField21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        OrdenServicioDirlogPanel.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, 80, 30));

        jTextField22.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        OrdenServicioDirlogPanel.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 65, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("Datos Consultor");
        OrdenServicioDirlogPanel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        OrdenServicioDirlogPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 870, 10));
        OrdenServicioDirlogPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 440, 10));
        OrdenServicioDirlogPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 350, 10));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        OrdenServicioDirlogPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 500, 50));

        btnBuscarConsultor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscarConsultor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busqueda-de-archivos-de-documentos-de-zoom-icono-4140-16.png"))); // NOI18N
        btnBuscarConsultor.setText("Buscar Consultor");
        OrdenServicioDirlogPanel.add(btnBuscarConsultor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar-usuario-icono-9786-16.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        OrdenServicioDirlogPanel.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 140, -1));

        btnNuevoConsultor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevoConsultor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documento.png"))); // NOI18N
        btnNuevoConsultor.setText("Nuevo Consultor");
        OrdenServicioDirlogPanel.add(btnNuevoConsultor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        btnBuscarOrden.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscarOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/administrador-de-archivos-icono-5210-16.png"))); // NOI18N
        btnBuscarOrden.setText("Buscar Orden");
        OrdenServicioDirlogPanel.add(btnBuscarOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 150, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 36));
        jLabel6.setText("ORDEN DE SERVICIO");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 36));
        jLabel9.setText("DIRLOG - PNP");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, 51));

        lblImagenEscudo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img.jpg"))); // NOI18N
        jPanel3.add(lblImagenEscudo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 110));

        OrdenServicioDirlogPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 520, -1));

        getContentPane().add(OrdenServicioDirlogPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 920, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void centrarFormulario(){
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize((pantalla.width),(pantalla.height));
        Dimension tamaño = OrdenServicioDirlogPanel.getSize();
        OrdenServicioDirlogPanel.setBounds((pantalla.width - tamaño.width)/2, (pantalla.height - tamaño.height)/2, (int)tamaño.getWidth(), (int)tamaño.getHeight());
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_btnCancelarActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField23ActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField28ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField29ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdenServicioDirlog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OrdenServicioDirlogPanel;
    private javax.swing.JButton btnBuscarConsultor;
    private javax.swing.JButton btnBuscarOrden;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevaOrden;
    private javax.swing.JButton btnNuevoConsultor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lblImagenEscudo1;
    // End of variables declaration//GEN-END:variables

}
